"use client";

import {
  Award,
  BarChart3,
  Bell,
  ChevronRight,
  ClipboardCheck,
  FileSearch,
  Flag,
  Flame,
  GitFork,
  HandHeart,
  Heart,
  HeartHandshake,
  Leaf,
  LayoutDashboard,
  LogOut,
  Menu,
  Moon,
  ScrollText,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Sun,
  Target,
  Trophy,
  Users,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  leaf: Leaf,
  "sliders-horizontal": SlidersHorizontal,
  target: Target,
  "hand-heart": HandHeart,
  "clipboard-check": ClipboardCheck,
  users: Users,
  "scroll-text": ScrollText,
  "shield-alert": ShieldAlert,
  "file-search": FileSearch,
  flag: Flag,
  award: Award,
  trophy: Trophy,
  sparkles: Sparkles,
  "git-fork": GitFork,
  "bar-chart-3": BarChart3,
  settings: Settings,
  bell: Bell,
  search: Search,
  menu: Menu,
  "log-out": LogOut,
  sun: Sun,
  moon: Moon,
  "chevron-right": ChevronRight,
  sprout: Sprout,
  flame: Flame,
  "heart-handshake": HeartHandshake,
  "shield-check": ShieldCheck,
  heart: Heart,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = map[name] ?? LayoutDashboard;
  return <Cmp className={className} />;
}
